### ISSUE TITLE
Good place to ask about EFI stuff?

### ISSUE THREAD

**Issue by symgryph** [alive4ever/alive4ever.github.io#2]
Sorry to bother you again, I did manage to get EFI stuff working within OPENWRT, but output image doesn't boot. When listing the final image, it looked like there was a MBR partion, no GPT parition present. Code also looks like its designed to be using MBR. How did you get around this? Using on a computer that expects boot partition to be fat32, and to have a gpt partition type. Was wondering what is the best way to contact? Or even if you want to be bothered, since you probably have better things to do? If you don't want to be bothered I will happily go away.  My email is symgryph at gmail dot com. I can provide beer, etc. 

Thomas

**Comment by alive4ever** [comment]
You may manually convert the generated image from mbr to gpt using gdisk / sgdisk.

Append 1 MB to the existing lede-x86-64-combined-ext4-uefi.img (needed for storing gpt backup data). Note that the minimum size is 34*512 bytes (roughly 17 KB) if you aim for the minimum.

``dd if=/dev/zero of=./lede-x86-64-combined-ext4-uefi.img bs=1M count=1 oflags=append conv=notrunc``

Convert the image to gpt
``sgdisk -p ./lede-x86-64-combined-ext4-uefi.img``
``sgdisk -g ./lede-x86-64-combined-ext4-uefi.img``
``sgdisk -t 1:EF00 ./lede-x86-64-combined-ext4-uefi.img``
``sgdisk -p ./lede-x86-64-combined-ext4-uefi.img``

In order to add uefi support on openwrt buildsystem, could you provide me an access to a cloud vm (via ipv4) to build and test my development? I'll be glad to continue my work with the provided cloud vm.

**Comment by symgryph** [comment]
how many procs? how much memory?

Thomas J Munn

**Comment by alive4ever** [comment]
In addition to converting the generated lede-image to gpt, you also need to need to edit the corresponding grub.cfg entry and replace (hd0,msdos1) to (hd0,gpt1). ``losetup -P -f $IMAGEFILE`` can be used to map the image file as kernel loopback device which can be mounted, e.g. ``mount /dev/loop0p1 /mnt``

**Comment by symgryph** [comment]
I will run by my supervisor, since this is for a company and not personal. I don’t think there should be any problem, however.  We might want to have a mutually agreeable written document to keep us both safe.

Thomas

**Comment by alive4ever** [comment]
>We might want to have a mutually agreeable written document

Yeah, I leave the paperworks to you. I'll sign it after reviewing, of course.

Show me the cloud-vm and I'll start the development as soon as possible.

**Comment by symgryph** [comment]
what is your preferred email address?

Thomas J Munn

**Comment by alive4ever** [comment]
> what is your preferred email address?

alive4ever()live.com
